In [1]:
#The ML File of a Script should be done in a separate notebook
#from the Preprocessing version, for sevral reasons.

In [2]:
import pandas as pd
import numpy as np

In [3]:
data_preprocessed = pd.read_csv("Absenteeism_preprocessed.csv")

In [4]:
data_preprocessed.head()

Reason_1  Reason_2  Reason_3  Reason_4  Month Value  Day of Week  \
0         0         0         0         1            7            1   
1         0         0         0         0            7            1   
2         0         0         0         1            7            2   
3         1         0         0         0            7            3   
4         0         0         0         1            7            3   

   Transportation Expense  Distance to Work  Age  Daily Work Load Average  \
0                     289                36   33                  239.554   
1                     118                13   50                  239.554   
2                     179                51   38                  239.554   
3                     279                 5   39                  239.554   
4                     289                36   33                  239.554   

   Body Mass Index  Education  Children  Pets  Absenteeism Time in Hours  
0               30          0         2     1                          4  
1               31          0         1     0                          0  
2               31          0         0     0                          2  
3               24          0         2     0                          4  
4               30          0         2     1                          2

In [5]:
# We will now do a logistic regression

## Create the Targets

In [6]:
#We will use Logistic Regression- Classifying people into "Classes"

In [7]:
# We have to create 2 Classes: One of people who have been excessively
# absent, and another for people that have not

In [8]:
# To define the class we will take the MEDIAN TIME of Absenteeism.
# Everything above would be considered "Excessively Absent"

In [9]:
data_preprocessed["Absenteeism Time in Hours"].median()

3.0

In [10]:
#So the median is 3

In [11]:
#Anyone above or equal to a score of 3 will receive a 1

In [12]:
targets = np.where(data_preprocessed["Absenteeism Time in Hours"] > 
                   data_preprocessed["Absenteeism Time in Hours"].median(),1,0)

In [13]:
targets

array([1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0,
       1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1,
       0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1,
       0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1,
       0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0,
       1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1,
       0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1,
       1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1,
       0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0,
       0, 0, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 1, 0, 0,
       0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0,

In [14]:
data_preprocessed["Excessive Absenteeism"] = targets

In [15]:
data_preprocessed.head()

Reason_1  Reason_2  Reason_3  Reason_4  Month Value  Day of Week  \
0         0         0         0         1            7            1   
1         0         0         0         0            7            1   
2         0         0         0         1            7            2   
3         1         0         0         0            7            3   
4         0         0         0         1            7            3   

   Transportation Expense  Distance to Work  Age  Daily Work Load Average  \
0                     289                36   33                  239.554   
1                     118                13   50                  239.554   
2                     179                51   38                  239.554   
3                     279                 5   39                  239.554   
4                     289                36   33                  239.554   

   Body Mass Index  Education  Children  Pets  Absenteeism Time in Hours  \
0               30          0         2     1                          4   
1               31          0         1     0                          0   
2               31          0         0     0                          2   
3               24          0         2     0                          4   
4               30          0         2     1                          2   

   Excessive Absenteeism  
0                      1  
1                      0  
2                      0  
3                      1  
4                      0

In [16]:
targets.sum()/targets.shape[0]

0.45571428571428574

In [17]:
data_with_targets = data_preprocessed.drop(["Absenteeism Time in Hours", "Day of Week",
                                           "Daily Work Load Average", "Distance to Work"],axis=1)

In [18]:
data_with_targets is data_preprocessed

False

In [19]:
data_with_targets.head()

Reason_1  Reason_2  Reason_3  Reason_4  Month Value  \
0         0         0         0         1            7   
1         0         0         0         0            7   
2         0         0         0         1            7   
3         1         0         0         0            7   
4         0         0         0         1            7   

   Transportation Expense  Age  Body Mass Index  Education  Children  Pets  \
0                     289   33               30          0         2     1   
1                     118   50               31          0         1     0   
2                     179   38               31          0         0     0   
3                     279   39               24          0         2     0   
4                     289   33               30          0         2     1   

   Excessive Absenteeism  
0                      1  
1                      0  
2                      0  
3                      1  
4                      0

## Selecting the Inputs for Regression

In [20]:
data_with_targets.shape

(700, 12)

In [21]:
# we will use iloc for this. Iloc selects (slices) data by position
# when given rows and columns are wanted

In [22]:
#You want to select everything EXCEPT the Excessive Absenteeism column
#Iloc's arguments are iloc[row_indices,column_indices]
data_with_targets.iloc[:,0:14]
#In the first argument, you are selecting all rows.

Reason_1  Reason_2  Reason_3  Reason_4  Month Value  \
0           0         0         0         1            7   
1           0         0         0         0            7   
2           0         0         0         1            7   
3           1         0         0         0            7   
4           0         0         0         1            7   
..        ...       ...       ...       ...          ...   
695         1         0         0         0            5   
696         1         0         0         0            5   
697         1         0         0         0            5   
698         0         0         0         1            5   
699         0         0         0         1            5   

     Transportation Expense  Age  Body Mass Index  Education  Children  Pets  \
0                       289   33               30          0         2     1   
1                       118   50               31          0         1     0   
2                       179   38               31          0         0     0   
3                       279   39               24          0         2     0   
4                       289   33               30          0         2     1   
..                      ...  ...              ...        ...       ...   ...   
695                     179   40               22          1         2     0   
696                     225   28               24          0         1     2   
697                     330   28               25          1         0     0   
698                     235   32               25          1         0     0   
699                     291   40               25          0         1     1   

     Excessive Absenteeism  
0                        1  
1                        0  
2                        0  
3                        1  
4                        0  
..                     ...  
695                      1  
696                      0  
697                      1  
698                      0  
699                      0  

[700 rows x 12 columns]

In [23]:
#You can also do the same thing like this
data_with_targets.iloc[:,:-1]

Reason_1  Reason_2  Reason_3  Reason_4  Month Value  \
0           0         0         0         1            7   
1           0         0         0         0            7   
2           0         0         0         1            7   
3           1         0         0         0            7   
4           0         0         0         1            7   
..        ...       ...       ...       ...          ...   
695         1         0         0         0            5   
696         1         0         0         0            5   
697         1         0         0         0            5   
698         0         0         0         1            5   
699         0         0         0         1            5   

     Transportation Expense  Age  Body Mass Index  Education  Children  Pets  
0                       289   33               30          0         2     1  
1                       118   50               31          0         1     0  
2                       179   38               31          0         0     0  
3                       279   39               24          0         2     0  
4                       289   33               30          0         2     1  
..                      ...  ...              ...        ...       ...   ...  
695                     179   40               22          1         2     0  
696                     225   28               24          0         1     2  
697                     330   28               25          1         0     0  
698                     235   32               25          1         0     0  
699                     291   40               25          0         1     1  

[700 rows x 11 columns]

In [24]:
unscaled_inputs = data_with_targets.iloc[:,:-1]

# Standardizing the Data

In [25]:
# from sklearn.preprocessing import StandardScaler

# absenteeism_scaler = StandardScaler() #Currently it is empty

In [26]:
#We will use this to "Scale" our data; absenabsenteeism_scaler will
#be used to subtract the mean and divide by the standard deviation

### Go BACK to customize the Standardizations!!!

In [27]:
from sklearn.base import BaseEstimator, TransformerMixin
from sklearn.preprocessing import StandardScaler

#WE NOT BUILD A CUSTOM SCALER

class CustomScaler(BaseEstimator, TransformerMixin):
    
    def __init__(self,columns,copy=True,with_mean=True,with_std=True):
        self.scaler = StandardScaler(copy,with_mean,with_std)
        self.columns = columns
        self.mean_ = None
        self.var_ = None
        
    def fit(self, X, y=None):
        self.scaler.fit(X[self.columns],y)
        self.mean_ = np.mean(X[self.columns])
        self.var_ = np.var(X[self.columns])
        return self
    
    def transform(self, X, y=None, copy=None):
        init_col_order = X.columns
        X_scaled = pd.DataFrame(self.scaler.transform(X[self.columns]),columns=self.columns)
        X_not_scaled= X.loc[:,~X.columns.isin(self.columns)]
        return pd.concat([X_not_scaled,X_scaled],axis=1)[init_col_order]

In [28]:
unscaled_inputs.columns.values

array(['Reason_1', 'Reason_2', 'Reason_3', 'Reason_4', 'Month Value',
       'Transportation Expense', 'Age', 'Body Mass Index', 'Education',
       'Children', 'Pets'], dtype=object)

In [29]:
#We need to omit the dummy variables from this list

# columns_to_scale = ['Month Value',
#        'Day of Week', 'Transportation Expense', 'Distance to Work', 'Age',
#        'Daily Work Load Average', 'Body Mass Index',
#        'Children', 'Pets']

columns_to_omit= ["Reason_1", "Reason_2", "Reason_3", "Reason_4", "Education"]

In [30]:
columns_to_scale = [x for x in unscaled_inputs.columns.values if x not in columns_to_omit]

In [31]:
absenteeism_scaler= CustomScaler(columns_to_scale)

In [32]:
absenteeism_scaler.fit(unscaled_inputs)
#Calculates the mean and standard dev of each column

/Users/samirbhojwani/opt/anaconda3/lib/python3.7/site-packages/sklearn/base.py:197: FutureWarning: From version 0.24, get_params will raise an AttributeError if a parameter cannot be retrieved as an instance attribute. Previously it would return None.
  FutureWarning)


CustomScaler(columns=['Month Value', 'Transportation Expense', 'Age',
                      'Body Mass Index', 'Children', 'Pets'],
             copy=None, with_mean=None, with_std=None)

In [33]:
scaled_inputs = absenteeism_scaler.transform(unscaled_inputs)

In [34]:
#STANDARDIZATION OF THE DATA-
#Every value gets subtracted by the mean and divided by the 
#standard dev of its respective column

In [35]:
scaled_inputs

Reason_1  Reason_2  Reason_3  Reason_4  Month Value  \
0           0         0         0         1     0.182726   
1           0         0         0         0     0.182726   
2           0         0         0         1     0.182726   
3           1         0         0         0     0.182726   
4           0         0         0         1     0.182726   
..        ...       ...       ...       ...          ...   
695         1         0         0         0    -0.388293   
696         1         0         0         0    -0.388293   
697         1         0         0         0    -0.388293   
698         0         0         0         1    -0.388293   
699         0         0         0         1    -0.388293   

     Transportation Expense       Age  Body Mass Index  Education  Children  \
0                  1.005844 -0.536062         0.767431          0  0.880469   
1                 -1.574681  2.130803         1.002633          0 -0.019280   
2                 -0.654143  0.248310         1.002633          0 -0.919030   
3                  0.854936  0.405184        -0.643782          0  0.880469   
4                  1.005844 -0.536062         0.767431          0  0.880469   
..                      ...       ...              ...        ...       ...   
695               -0.654143  0.562059        -1.114186          1  0.880469   
696                0.040034 -1.320435        -0.643782          0 -0.019280   
697                1.624567 -1.320435        -0.408580          1 -0.919030   
698                0.190942 -0.692937        -0.408580          1 -0.919030   
699                1.036026  0.562059        -0.408580          0 -0.019280   

         Pets  
0    0.268487  
1   -0.589690  
2   -0.589690  
3   -0.589690  
4    0.268487  
..        ...  
695 -0.589690  
696  1.126663  
697 -0.589690  
698 -0.589690  
699  0.268487  

[700 rows x 11 columns]

In [36]:
scaled_inputs.shape

(700, 11)

In [37]:
#Overfitting test data is when you fit the data SO well that when it
#comes time to run it with real, new data, it fails miserably.

In [38]:
#One way to deal with ovrfitting is to "Hide" a subset of the data set
#from the algorithm
#We train the model with most of the data but not all of it

In [39]:
# We will split the model on TRAIN and TEST so that we can test the 
# model's accuracy that it has never seen before (Test)

In [40]:
from sklearn.model_selection import train_test_split

## Splitting the Data

In [41]:
train_test_split(scaled_inputs, targets)

[     Reason_1  Reason_2  Reason_3  Reason_4  Month Value  \
 150         0         0         0         1    -1.244823   
 155         0         0         0         1    -0.959313   
 44          0         0         0         1     0.753746   
 324         0         0         0         1     1.324766   
 45          0         0         0         1     0.753746   
 ..        ...       ...       ...       ...          ...   
 39          0         0         0         1     0.468236   
 106         0         0         0         1     1.610276   
 577         0         0         1         0    -1.530333   
 397         0         0         0         1    -0.959313   
 650         0         0         0         1    -0.959313   
 
      Transportation Expense       Age  Body Mass Index  Education  Children  \
 150                0.040034 -1.320435        -0.643782          0 -0.019280   
 155                1.036026 -0.692937        -0.878984          0 -0.919030   
 44                -1.0163

In [42]:
# This output will consist of FOUR ARRAYS:
# 1. A training dataset with inputs
# 2. A training dataset with targts
# 3. A test dataset with inputs
# 4. A test dataset with targets

In [43]:
# You should specify the Train Size with a reasonable split betweeen
# Train and test being 80-20
x_train,x_test,y_train,y_test = train_test_split(scaled_inputs,targets, train_size = 0.8, random_state=20)

In [44]:
print(x_train.shape,y_train.shape)

(560, 11) (560,)


In [45]:
print(x_test.shape,y_test.shape)

(140, 11) (140,)


In [46]:
# There are 14 Input Variables, and 1 Target Variable

In [47]:
# REMEMBER: ML is 90% PREPROCESSING AND 10% MODELLING!!

## Logistic Regression with sklearn

In [48]:
from sklearn.linear_model import LogisticRegression
from sklearn import metrics

## Training the model

In [49]:
reg = LogisticRegression()

In [50]:
reg.fit(x_train,y_train)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='auto', n_jobs=None, penalty='l2',
                   random_state=None, solver='lbfgs', tol=0.0001, verbose=0,
                   warm_start=False)

In [51]:
reg.score(x_train,y_train)
#If we input targets and inputs, this will return the mean accuracy on
#the given test data and labels

0.7732142857142857

In [52]:
#So we can conclude that our model has an accuracy of 0.8
#In other words, our model learned to classify 80% of the observations
#correctly.

### Manually check the accuracy

In [53]:
#If we want to find the accuracy of a model manually, we must see the
#outputs and compare them manually with the targets

In [54]:
model_outputs = reg.predict(x_train) #We are predicting the outputs
model_outputs

array([0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0,
       0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1,
       1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 1, 0,
       0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0,
       0, 1, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0,
       1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0,
       0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1,
       1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1,
       1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1,
       0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1,
       0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0,
       0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0,

In [55]:
y_train

array([0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0,
       1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1,
       1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0,
       0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 1,
       1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0,
       0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1,
       0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0,
       0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1,
       1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0,
       1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0,
       0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0,
       1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0,

In [56]:
model_outputs == y_train #we are matching x_train and y_train to see
#that if there is a match then return true, otherwise, false

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True, False,  True, False, False,  True,  True,  True,  True,
       False,  True, False,  True, False, False,  True,  True,  True,
       False,  True,  True,  True,  True,  True,  True,  True,  True,
       False, False, False, False,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True, False,  True,  True,  True,
        True,  True,  True,  True,  True, False,  True,  True,  True,
        True,  True,  True,  True,  True,  True, False,  True,  True,
        True,  True,  True, False,  True,  True,  True,  True,  True,
       False,  True, False,  True,  True, False, False, False,  True,
        True,  True,  True,  True,  True,  True,  True, False,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True, False,  True,  True,  True,  True,
       False,  True,  True,  True,  True, False,  True,  True,  True,
        True,  True,

In [57]:
np.sum((model_outputs == y_train))

433

In [58]:
model_outputs.shape[0]

560

In [59]:
np.sum((model_outputs == y_train))/model_outputs.shape[0]

0.7732142857142857

In [60]:
#From manually checking, we get the EXACT same score as we did when
#using reg.score(x_train,y_train)

## Finding the Intercept and the Coefficients

In [61]:
#The intercepts and coefficients can be found pretty easily
reg.intercept_

array([-1.6474549])

In [62]:
reg.coef_

array([[ 2.80019733,  0.95188356,  3.11555338,  0.83900082,  0.1589299 ,
         0.60528415, -0.16989096,  0.27981088, -0.21053312,  0.34826214,
        -0.27739602]])

In [63]:
#Now we have to go back to using UNSCALED_INPUTS since it is a dataframe
#while scaled_inputs is an array
unscaled_inputs.columns.values

array(['Reason_1', 'Reason_2', 'Reason_3', 'Reason_4', 'Month Value',
       'Transportation Expense', 'Age', 'Body Mass Index', 'Education',
       'Children', 'Pets'], dtype=object)

In [64]:
feature_name = unscaled_inputs.columns.values

In [65]:
summary_table = pd.DataFrame(columns=["Feature name"],data=feature_name)

In [66]:
summary_table["Coefficient"] = np.transpose(reg.coef_)
#NOTE: we must transpose these arrays because by default, nd arrays
#are rows, not columns

In [67]:
summary_table

Feature name  Coefficient
0                 Reason_1     2.800197
1                 Reason_2     0.951884
2                 Reason_3     3.115553
3                 Reason_4     0.839001
4              Month Value     0.158930
5   Transportation Expense     0.605284
6                      Age    -0.169891
7          Body Mass Index     0.279811
8                Education    -0.210533
9                 Children     0.348262
10                    Pets    -0.277396

In [68]:
summary_table.index = summary_table.index+1
summary_table.loc[0] = ["Intercept", reg.intercept_[0]]
summary_table = summary_table.sort_index()
summary_table

Feature name  Coefficient
0                Intercept    -1.647455
1                 Reason_1     2.800197
2                 Reason_2     0.951884
3                 Reason_3     3.115553
4                 Reason_4     0.839001
5              Month Value     0.158930
6   Transportation Expense     0.605284
7                      Age    -0.169891
8          Body Mass Index     0.279811
9                Education    -0.210533
10                Children     0.348262
11                    Pets    -0.277396

## Interpreting the Coefficients

In [69]:
#These coefficients are also called WEIGHTS while the intercept is the
#Bias. The closer the weights are to ZERO, the smaller the weight

In [70]:
#Whichever weight is bigger, its corresponding feature is more important

In [71]:
summary_table["Odds_ratio"]=np.exp(summary_table.Coefficient)
#This adds the exponentials of our coefficients

In [72]:
summary_table

Feature name  Coefficient  Odds_ratio
0                Intercept    -1.647455    0.192539
1                 Reason_1     2.800197   16.447892
2                 Reason_2     0.951884    2.590585
3                 Reason_3     3.115553   22.545903
4                 Reason_4     0.839001    2.314054
5              Month Value     0.158930    1.172256
6   Transportation Expense     0.605284    1.831773
7                      Age    -0.169891    0.843757
8          Body Mass Index     0.279811    1.322880
9                Education    -0.210533    0.810152
10                Children     0.348262    1.416604
11                    Pets    -0.277396    0.757754

In [73]:
summary_table.sort_values("Odds_ratio", ascending=False)

Feature name  Coefficient  Odds_ratio
3                 Reason_3     3.115553   22.545903
1                 Reason_1     2.800197   16.447892
2                 Reason_2     0.951884    2.590585
4                 Reason_4     0.839001    2.314054
6   Transportation Expense     0.605284    1.831773
10                Children     0.348262    1.416604
8          Body Mass Index     0.279811    1.322880
5              Month Value     0.158930    1.172256
7                      Age    -0.169891    0.843757
9                Education    -0.210533    0.810152
11                    Pets    -0.277396    0.757754
0                Intercept    -1.647455    0.192539

In [74]:
#The highest coefficient is the most important
#IF a coefficient is around 0 or its odds ration is around 1, that 
#means that the feature is not particularly important.
#For coefficient, if it is 0, the feature value gets multiplied by 0
#therefore it is not considered important

In [75]:
#The Odds ration means that for a unit change in the standardized 
#feature, the odds increase by a multiple equal to the odds ratio.
#Therefore, an odds ration of 1 = no change

In [76]:
summary_table.iloc[10]

Feature name    Children
Coefficient     0.348262
Odds_ratio        1.4166
Name: 10, dtype: object

In [77]:
#So we can see that Daily Workload has a low coefficient and an odds
#ratio at about 1. So it is insignificant. 

## You need to go back and omit the dummy variables
## from the standardization

In [78]:
# It is bad practice to standardize the dummies because when you 
# standardize, you lose the whole interpretability of a dummy because
# the dummies were only 0 and 1. So they should NOT be standardized

In [79]:
# Therefore you need to go back to the checkpoint of standardizing the
# data and NOT Standardize the dummies.

## Interpreting Important Predictors

In [80]:
#REMEMBER: The further away from 0 a coefficient is, the bigger its
#importance

#SO it seems that the most salient predictors at the moment are the 
#4 Reasons for absence, the Transportation expens, BMI, Education, 
#Children, and pets

In [81]:
summary_table.sort_values("Odds_ratio", ascending=False)

Feature name  Coefficient  Odds_ratio
3                 Reason_3     3.115553   22.545903
1                 Reason_1     2.800197   16.447892
2                 Reason_2     0.951884    2.590585
4                 Reason_4     0.839001    2.314054
6   Transportation Expense     0.605284    1.831773
10                Children     0.348262    1.416604
8          Body Mass Index     0.279811    1.322880
5              Month Value     0.158930    1.172256
7                      Age    -0.169891    0.843757
9                Education    -0.210533    0.810152
11                    Pets    -0.277396    0.757754
0                Intercept    -1.647455    0.192539

In [82]:
# The weights of Month Value, Daily work load, distance to work and
# Day of the week are almost ZERO, with Odds ratios close to 1, so
# it seems that they are negligible. They will not affect our model

In [83]:
# So the most crucial reason for excessive absence is Reason 3 (poisoning)

In [84]:
# A negative Coefficient (Example: Pets) 

In [85]:
# The intercept has no real purpose other than to "Calibrate" the model
# It is a type of BIAS. Without an intercept, each prediction would be 
# off the mark by precisely that value

## Backward Elimination

In [86]:
# The weights of Month Value, Daily work load, distance to work and
# Day of the week are almost ZERO, with Odds ratios close to 1, so
# it seems that they are negligible.

In [87]:
#Therefore we can simplify our model by removing all features that have
#close to no contribution to the model.

In [88]:
# So we will go back to line 17 of the code and rerun it, taking out
# those 3 features.

## Testing the ML Model

In [89]:
#At this stage our train accuracy is around 77%,
#But we have still not tried our test data that it has not seen yet

In [90]:
# We will be testing manually
#Test 1: Find the accuracy:

reg.score(x_test,y_test)

0.75

In [91]:
#Test accuracy is always less than the train accuracy (often 10%)

In [92]:
predicted_proba= reg.predict_proba(x_test)
predicted_proba

array([[0.71340413, 0.28659587],
       [0.58724228, 0.41275772],
       [0.44020821, 0.55979179],
       [0.78159464, 0.21840536],
       [0.08410854, 0.91589146],
       [0.33487603, 0.66512397],
       [0.29984576, 0.70015424],
       [0.13103971, 0.86896029],
       [0.78625404, 0.21374596],
       [0.74903632, 0.25096368],
       [0.49397598, 0.50602402],
       [0.22484913, 0.77515087],
       [0.07129151, 0.92870849],
       [0.73178133, 0.26821867],
       [0.30934135, 0.69065865],
       [0.5471671 , 0.4528329 ],
       [0.55052275, 0.44947725],
       [0.5392707 , 0.4607293 ],
       [0.40201117, 0.59798883],
       [0.05361575, 0.94638425],
       [0.7003009 , 0.2996991 ],
       [0.78159464, 0.21840536],
       [0.42037128, 0.57962872],
       [0.42037128, 0.57962872],
       [0.24783565, 0.75216435],
       [0.74566259, 0.25433741],
       [0.51017274, 0.48982726],
       [0.85690195, 0.14309805],
       [0.20349733, 0.79650267],
       [0.78159464, 0.21840536],
       [0.

In [93]:
predicted_proba[:,1]

array([0.28659587, 0.41275772, 0.55979179, 0.21840536, 0.91589146,
       0.66512397, 0.70015424, 0.86896029, 0.21374596, 0.25096368,
       0.50602402, 0.77515087, 0.92870849, 0.26821867, 0.69065865,
       0.4528329 , 0.44947725, 0.4607293 , 0.59798883, 0.94638425,
       0.2996991 , 0.21840536, 0.57962872, 0.57962872, 0.75216435,
       0.25433741, 0.48982726, 0.14309805, 0.79650267, 0.21840536,
       0.36956558, 0.67906035, 0.68502567, 0.52868083, 0.21840536,
       0.53506551, 0.22147081, 0.73692105, 0.40498044, 0.60505988,
       0.21075848, 0.45224466, 0.23751292, 0.39833498, 0.82755447,
       0.56797575, 0.69113325, 0.28659587, 0.21935267, 0.2033097 ,
       0.57628256, 0.3294664 , 0.66512397, 0.26949499, 0.83321968,
       0.43491525, 0.88374612, 0.23127072, 0.33415858, 0.34432939,
       0.69909345, 0.65494263, 0.29244941, 0.79200758, 0.20750276,
       0.26840558, 0.08708566, 0.22147081, 0.73245417, 0.30530219,
       0.22147081, 0.29014408, 0.90438191, 0.46061297, 0.60174

In [94]:
#This gives the probability of absenteeism for each test data

## Save the Model for Future use

In [95]:
#Saving the model is basically the equivalent to saving the reg. object

In [96]:
#We use the python module Pickle. Pickling is the process of converting
#a python object into a character stream

In [97]:
# So in laymans terms we will save the reg object into a file

In [98]:
#Pickling allows people to send files via emails, chats etc. it is like
#compressing the ML algorithm

In [99]:
import pickle

In [100]:
with open("model","wb") as file:
    pickle.dump(reg,file)
    
#model = file name

In [101]:
# We must save the absenteeism_scaler too
# The info in the absenteeism_Scaler model is used to preprocess any new
# data that would come in the future

In [102]:
with open("scaler","wb") as file:
    pickle.dump(absenteeism_scaler,file)

In [103]:
#Once again, ‘pickle’ is the standard Python tool for serialization and deserialization. In simple words, pickling means: converting a Python object (no matter what) into a string of characters. Logically, unpickling is about converting a string of characters (that has been pickled) into a Python object.

## Deploying a Model

In [104]:
#Now we need to create a mechanism to load the saved model and make 
#predictions

In [105]:
#YOu could rerun your code each time, but this is inefficient and prone
#to error
#In practice, we prefer always creating a MODULE. Storing code in a 
#module allows you to reuse it without trouble

In [106]:
# To create a module you need to create several classes and save it in
# .py format.